version: "3.7"

x-restart-policy: &restart_policy
  restart: unless-stopped


services:
  load_balancer:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - ipc_server

  ipc_server:
    <<: *restart_policy
    image: localhost/ipc_server
    build:
      context: ./ipc_server
      dockerfile: Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./ipc_server/media.db
        target: /db/media.db

  bot:
    <<: *restart_policy
    image: localhost/bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    tty: true
    environment:
      - TOKEN=YOUR_BOT_TOKEN_HERE
      - IPC_BASE_URI=http://ipc_server
      - PREMIUM_ROLE_ID=YOUR_PREMIUM_ROLE_ID
      - PREMIUM_SERVER_ID=YOUR_SERVER_ID
    depends_on:
      - ipc_server

  web:
    <<: *restart_policy
    image: localhost/web
    build:
      context: ./web
      dockerfile: Dockerfile
    tty: true
    environment:
      - IPC_DOMAIN=ipc_server
      - CLIENT_ID=CLIENT_ID_HERE
      - CLIENT_SECRET=CLIENT_SECRET_HERE
      - REDIRECT_URI=http://localhost/callback
      - SIGN_PASS=JWT_SIGN_PASSPHRASE
    depends_on:
      - ipc_server

volumes:
  media_db:
