version: "3.7"

x-restart-policy: &restart_policy
  restart: unless-stopped


services:
  load_balancer:
    image: localhost/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
      - ipc_server

  ipc_server:
    <<: *restart_policy
    image: localhost/ipc_server
    build:
      context: ./ipc_server
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/db

  bot:
    <<: *restart_policy
    image: localhost/bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    tty: true
    environment:
      - TOKEN=TOKEN_HERE
    depends_on:
      - ipc_server

  web:
    <<: *restart_policy
    image: localhost/web
    build:
      context: ./web
      dockerfile: Dockerfile
    tty: true
    environment:
      - IPC_DOMAIN=ipc_server
      - CLIENT_ID=YOUR_CLIENT_ID
      - CLIENT_SECRET=YOUR_CLIENT_SECRET_HERE
      - REDIRECT_URI=http://localhost/callback
      - SIGN_PASS=JWT_SIGN_PASSPHRASE
    depends_on:
      - ipc_server

volumes:
  media_db:
